# Configuration of generators (defaults illustrated)
---
generator_args:
  jsonschema: {}
  owl:
    mergeimports: true
    metaclasses: true
    type_objects: true
  includes:
    - jsonschema
    - python
    - owl
    - shex
    - shacl
    - prefixmap
  excludes:
    - graphql
    - sqlschema
    - protobuf
